### ISSUE TITLE
Uncaught TypeError: L is not a constructor

### ISSUE THREAD

**Issue by billplaysonline** [iitc-project/ingress-intel-total-conversion#1162] opened 2016-12-25 03:32 UTC
gen_dashboard_c906315….js:53 Uncaught TypeError: L is not a constructor
    at new Ce (gen_dashboard_c906315….js:53)
    at new Le (gen_dashboard_c906315….js:53)
    at Function.a.l (gen_dashboard_c906315….js:1)
    at new Te (gen_dashboard_c906315….js:56)
    at new R (gen_dashboard_c906315….js:63)
    at Function.a.l (gen_dashboard_c906315….js:1)
    at Pe (gen_dashboard_c906315….js:192)
    at Oe.j (gen_dashboard_c906315….js:280)
    at Oe.I (gen_dashboard_c906315….js:283)
    at sc (gen_dashboard_c906315….js:22)
    
    
    A web browser built for speed, simplicity, and security
    Get help with using Chrome Report an issue
    Version 55.0.2883.87 m (64-bit)
Google Chrome is up to date.

IITC: Ingress intel map total conve...
0.26.0.20161003.4825

No plugins.

https://www.ingress.com/intel?ll=42.007105,-88.061291&z=17&pll=42.007105,-88.061291

When IITC starts on my laptop or my Moto X pure.
In the debug log I see the title error.

The error is coming from within the ingress scripts I think.
But I think I have tracked down a trigger that causes this error.
I have the script up and my developer tools on watching the log.

Refresh the script.    No error.
Open the chat screen. The error occurs, but only on the first time.

The chat module will cause the error on its first opening after start.

**Comment by McBen** [comment] 2016-12-25 09:20
duplicate of [#964](https://github.com/iitc-project/ingress-intel-total-conversion/issues/964)

**Comment by billplaysonline** [comment] 2016-12-27 20:53
I have taken another step forward on this problem but I am not happy with what I got.
Essentially adding a "console.log ('#### see if slight delay changes problem.$$$$$$$$$$$$$$$$$$$$$$$$$$');" at the beginning of the function  changes timing so the error doesn't occur. I am not sure where to go from here. I hate this kind of bug.
[ChatFunctionTimmingIssue.txt](https://github.com/iitc-project/ingress-intel-total-conversion/files/674633/ChatFunctionTimmingIssue.txt)

**Comment by billplaysonline** [comment] 2016-12-27 20:55
Something is getting changed somewhere to cause this problem. I hope there is someone that can take this over. It is getting above my paygrade, capabilities.

**Comment by McBen** [comment] 2016-12-27 21:24
as said in #964 : error is 'cause by stock-intels function L and iitc's leaflet L.
possible patch PR #1164 .. since it would kill every 3rd-party plugin the PR is just a preparation for a fix in future.

but in the end this error message is produced by dead/unused stock-intel code and so is not critical.

**Comment by billplaysonline** [comment] 2016-12-27 22:49
Ok, Just for grins
 I just tried to search all the JS files for "L" and replace with Lii.
Also had to rename the files in External that started with L. to Lii. But broke it pretty good. I will stop messing with this and look at an easier bug to chase.

**Closed** 2016-12-27 22:49 UTC
