### ISSUE TITLE
New Tab with only "for the User" Messages

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [iitc-project/ingress-intel-total-conversion#343] opened 2013-06-01 22:39 UTC
Make a plugin were (or implmente in iitc) with a new chat tab, were only messages adressed to the useres are visible.
![2013-06-02 00_35_07-ingress intel map](https://f.cloud.github.com/assets/4589916/595555/0b9b1cb8-cb0c-11e2-9a14-a2db0fe3d5f6.png)

**Comment by nhamer** [comment] 2017-01-19 04:44
Can this issue be closed as a duplicate of #133 ?

**Comment by 5t0rmr1d3r** [comment] 2017-05-15 04:53
@nhamer yes, issue can be closed...

**Closed** 2017-10-18 05:26 UTC
